In [ ]:
# import libraries
import pandas as pd
import numpy
import sklearn.neighbors._base
import sys
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
import missingpy

In [ ]:
# mount google drive 
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# load google drive csv file
df = pd.read_csv("/content/drive/MyDrive/Statistics Project 2/Data/Raw/landfillData_NEW.csv")

In [ ]:
df

,Index,emissionsTS,emissiondate,emissiontime,CH4,CO2,O2,otherGas,internalPressure_Hg,fau_degF,...,dew,humidity,precip,windspeed,winddirection,sealevelpressure,cloudcover,visibility,solarradiation,conditions
0,0,9/1/2020 0:02,9/1/2020,0:02:18,34.3,28.9,0.2,36.6,29.25,88.2,...,56.1,75.40,0.0,5.6,273.0,1011.2,0.0,9.9,0.0,Clear
1,1,9/1/2020 0:12,9/1/2020,0:12:18,34.4,28.9,0.2,36.5,29.25,88.1,...,56.1,75.40,0.0,5.6,273.0,1011.2,0.0,9.9,0.0,Clear
2,2,9/1/2020 0:22,9/1/2020,0:22:19,34.4,29.0,0.6,36.0,29.25,88.3,...,56.1,75.40,0.0,5.6,273.0,1011.2,0.0,9.9,0.0,Clear
3,3,9/1/2020 0:32,9/1/2020,0:32:19,34.5,29.0,0.3,36.2,29.25,88.1,...,56.1,75.40,0.0,5.6,273.0,1011.2,0.0,9.9,0.0,Clear
4,4,9/1/2020 0:42,9/1/2020,0:42:19,34.5,29.0,0.2,36.3,29.25,88.4,...,56.1,75.40,0.0,5.6,273.0,1011.2,0.0,9.9,0.0,Clear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101161,101161,9/22/2022 15:33,9/22/2022,15:33:29,47.2,32.5,0.0,20.3,29.18,86.4,...,40.4,16.96,0.0,5.1,271.0,1010.3,2.7,9.9,406.0,Clear
101162,101162,9/22/2022 15:43,9/22/2022,15:43:29,47.3,32.4,0.0,20.3,29.18,86.6,...,40.4,16.96,0.0,5.1,271.0,1010.3,2.7,9.9,406.0,Clear
101163,101163,9/22/2022 15:53,9/22/2022,15:53:30,47.3,32.4,0.0,20.3,29.18,86.4,...,40.4,16.96,0.0,5.1,271.0,1010.3,2.7,9.9,406.0,Clear
101164,101164,9/22/2022 16:03,9/22/2022,16:03:30,47.3,32.4,0.0,20.3,29.18,86.4,...,42.3,17.87,0.0,1.8,345.0,1009.4,3.8,9.9,287.0,Clear
101165,101165,9/22/2022 16:08,9/22/2022,16:08:38,47.3,32.4,0.0,20.3,NaN,NaN,...,42.3,17.87,0.0,1.8,345.0,1009.4,3.8,9.9,287.0,Clear

In [ ]:
# missingpy does not take any string type so will temporarily remove
#inserted back with excel
df = df.drop(['Index','emissionsTS', 'emissiondate', 'emissiontime', 'weatherTS', 'weatherDate', 'weatherTime','conditions'], axis=1)

In [ ]:
df

,Index,CH4,CO2,O2,otherGas,internalPressure_Hg,fau_degF,flowMain_SCFM,tempdegf,dew,humidity,precip,windspeed,winddirection,sealevelpressure,cloudcover,visibility,solarradiation
0,0,34.3,28.9,0.2,36.6,29.25,88.2,147.985348,64.1,56.1,75.40,0.0,5.6,273.0,1011.2,0.0,9.9,0.0
1,1,34.4,28.9,0.2,36.5,29.25,88.1,152.380952,64.1,56.1,75.40,0.0,5.6,273.0,1011.2,0.0,9.9,0.0
2,2,34.4,29.0,0.6,36.0,29.25,88.3,156.043956,64.1,56.1,75.40,0.0,5.6,273.0,1011.2,0.0,9.9,0.0
3,3,34.5,29.0,0.3,36.2,29.25,88.1,153.601954,64.1,56.1,75.40,0.0,5.6,273.0,1011.2,0.0,9.9,0.0
4,4,34.5,29.0,0.2,36.3,29.25,88.4,151.648352,64.1,56.1,75.40,0.0,5.6,273.0,1011.2,0.0,9.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101161,101161,47.2,32.5,0.0,20.3,29.18,86.4,121.855922,91.3,40.4,16.96,0.0,5.1,271.0,1010.3,2.7,9.9,406.0
101162,101162,47.3,32.4,0.0,20.3,29.18,86.6,121.123321,91.3,40.4,16.96,0.0,5.1,271.0,1010.3,2.7,9.9,406.0
101163,101163,47.3,32.4,0.0,20.3,29.18,86.4,123.321123,91.3,40.4,16.96,0.0,5.1,271.0,1010.3,2.7,9.9,406.0
101164,101164,47.3,32.4,0.0,20.3,29.18,86.4,121.855922,92.0,42.3,17.87,0.0,1.8,345.0,1009.4,3.8,9.9,287.0
101165,101165,47.3,32.4,0.0,20.3,NaN,NaN,122.344322,92.0,42.3,17.87,0.0,1.8,345.0,1009.4,3.8,9.9,287.0

In [ ]:
#beging imputation using random forest
from missingpy import MissForest
imputer = MissForest()
df_new = imputer.fit_transform(df)

/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(

Iteration: 0

/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(

Iteration: 1

/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(

Iteration: 2

/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(

Iteration: 3

/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(

Iteration: 4

/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(

Iteration: 5

In [ ]:
# change from array to DataFrame type
# save as csv
th = pd.DataFrame(df_new)
th.to_csv('imputed.csv', sep =',')